apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: ingress
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: ingress
      component: nginx
  template:
      metadata:
          labels:
            purpose: ingress
            component: nginx
      spec:
        containers:
        - name: nginx
          image: srinunaik208/app2:v1 
---
apiVersion: v1 
kind: Service
metadata:
  name: app2 
  labels:
     purpose: ingress
     component: nginx
spec:
  selector:
    purpose: ingress
    component: nginx
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{HTTPS: 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:824333137275:certificate/d3169da7-19cb-420c-9a38-dfd1177f24d5
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
   ingressClassName: alb
   rules:
   - host: app2.srinunayak.online
     http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2 
            port:
              number: 80

    
    
      